version: '3'
services:
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: itseed_api
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
